# Generated by Django 2.1.7 on 2019-03-24 23:14

import uuid

import django.core.validators
from django.db import migrations, models

from GameCenter.apps.games.storage import upload_file_to, GameStorage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=10)),
                ('logo', models.ImageField(storage=GameStorage(), upload_to=upload_file_to)),
                ('file', models.FileField(storage=GameStorage(), upload_to=upload_file_to,
                                          validators=[django.core.validators.FileExtensionValidator(
                                              allowed_extensions=['zip'])])),
            ],
            options={
                'ordering': ('id', 'name', 'version'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('name', 'version')},
        ),
    ]
