# Generated by Django 2.1.7 on 2019-03-15 20:34

import uuid

import django.core.validators
from django.db import migrations, models

import games.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('logo', models.ImageField(upload_to=games.storage.upload_file)),
                ('version', models.CharField(max_length=10)),
                ('file', models.FileField(storage=games.storage.OverwriteStorage(), upload_to=games.storage.upload_file,
                                          validators=[django.core.validators.FileExtensionValidator(
                                              allowed_extensions=['zip'])])),
            ],
            options={
                'ordering': ('name', 'version', 'id'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('name', 'version')},
        ),
    ]
