# Generated by Django 2.1.7 on 2019-03-16 21:44

from django.db import migrations, models

import games.storage


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0003_auto_20190317_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(null=True, storage=games.storage.OverwriteStorage(),
                                    upload_to=games.storage.upload_file),
        ),
    ]
