# Generated by Django 2.1.7 on 2019-03-16 21:53

import django.core.validators
from django.db import migrations, models

import games.storage


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0004_auto_20190317_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='file',
            field=models.FileField(blank=True, null=True, storage=games.storage.OverwriteStorage(),
                                   upload_to=games.storage.upload_file, validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=games.storage.OverwriteStorage(),
                                    upload_to=games.storage.upload_file),
        ),
    ]
