# Generated by Django 2.1.7 on 2019-03-16 22:36

import django.core.validators
from django.db import migrations, models

import games.storage


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0005_auto_20190317_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='file',
            field=models.FileField(storage=games.storage.OverwriteStorage(), upload_to=games.storage.upload_file,
                                   validators=[
                                       django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(storage=games.storage.OverwriteStorage(), upload_to=games.storage.upload_file),
        ),
    ]
